#include <stdio.h>

static const char* help = ";button_optorelay, button_led Standard module_mode for all slots \n"
"\n"
    ";Button options: button_inverse\n"
    ";Button trigger: [device_name]/button_[num_of_slot]:val(0-1)\n"
"\n"
    ";Optorelay options: optorelay_default_high=val(0-1), optorelay_inverse=val(0-1)\n"
    ";Optorelay action: [device_name]/optorelay_[num_of_slot]:val(0-1)\n"
"\n"
    ";Led options: led_default_high=val(0-1), led_inverse=val(0-1)\n"
    ";Led action: [device_name]/led_[num_of_slot]:val(0-1)\n"
"\n"
    ";Standard module_mode: 3n_mosfet \n"
"\n"
    ";encoderPWM Standard module_mode for all slots \n"
    ";encoderPWM options: num_of_pos:val(0-1), incremental, absolute\n"
    ";encoderPWM trigger: [device_name]/encoderInc_[num_of_slot]:val(+1/-1)\n"
    ";encoderPWM trigger: [device_name]/encoderAbs_[num_of_slot]:val(0-num_of_pos)\n"
"\n"
    ";audio_player_mono module_mode Special for SLOT_0:  \n"
    ";audio_player_mono module_options: volume:val, delay:val\n"
    ";audio_player_mono action: [device_name]/play_track:val(=num, +num, -num)\n"
                       "[device_name]/player_stop:val(need, but ignored)\n"
                       "[device_name]/player_pause:val(need, but ignored)\n"
                       "[device_name]/set_volume:val(=num, +num, -num)\n";